"""Reality Gate verification primitives for PhiOS."""

from .local_http import (
    LocalHttpObservation,
    LocalHttpObservationError,
    LocalHttpStateProvider,
    StdlibLoopbackHttpStateProvider,
    UnavailableLocalHttpStateProvider,
    local_http_url_error,
)
from .local_json import (
    JSON_NUMERIC_TRANSITION_PREDICATES,
    JSON_SCALAR_PREDICATES,
    JSON_STRUCTURAL_PREDICATES,
    JsonContractClause,
    JsonMixedContractClause,
    JsonNumericTransitionClause,
    JSON_TYPE_NAMES,
    evaluate_json_contract_clause,
    evaluate_json_mixed_contract_clause,
    evaluate_json_numeric_transition_pair,
    evaluate_json_scalar_predicate,
    extract_json_numeric_transition_value,
    evaluate_json_structural_predicate,
    json_numeric_transition_expected_type,
    json_numeric_transition_predicate_error,
    json_pointer_error,
    json_scalar_predicate_error,
    json_scalar_predicate_expected_type,
    json_structural_predicate_error,
    json_structural_predicate_expected_type,
    json_type_matches,
    json_type_name,
    resolve_json_pointer,
    strict_json_loads,
)
from .local_network import (
    InterfaceObservation,
    InterfaceObservationError,
    InterfaceStateProvider,
    PsutilInterfaceStateProvider,
)
from .local_socket import (
    PsutilTcpListenerStateProvider,
    TcpListenerObservation,
    TcpListenerObservationError,
    TcpListenerStateProvider,
)
from .models import (
    RealityClaim,
    RealityClaimKind,
    RealityVerdict,
    RealityVerificationResult,
)
from .service import RealityVerificationService

__all__ = [
    "JSON_NUMERIC_TRANSITION_PREDICATES",
    "JSON_SCALAR_PREDICATES",
    "JSON_STRUCTURAL_PREDICATES",
    "JsonContractClause",
    "JsonMixedContractClause",
    "JsonNumericTransitionClause",
    "JSON_TYPE_NAMES",
    "InterfaceObservation",
    "InterfaceObservationError",
    "InterfaceStateProvider",
    "LocalHttpObservation",
    "LocalHttpObservationError",
    "LocalHttpStateProvider",
    "PsutilInterfaceStateProvider",
    "PsutilTcpListenerStateProvider",
    "RealityClaim",
    "RealityClaimKind",
    "RealityVerdict",
    "RealityVerificationResult",
    "RealityVerificationService",
    "StdlibLoopbackHttpStateProvider",
    "TcpListenerObservation",
    "TcpListenerObservationError",
    "TcpListenerStateProvider",
    "UnavailableLocalHttpStateProvider",
    "evaluate_json_contract_clause",
    "evaluate_json_mixed_contract_clause",
    "evaluate_json_numeric_transition_pair",
    "evaluate_json_scalar_predicate",
    "extract_json_numeric_transition_value",
    "evaluate_json_structural_predicate",
    "json_numeric_transition_expected_type",
    "json_numeric_transition_predicate_error",
    "json_pointer_error",
    "json_scalar_predicate_error",
    "json_scalar_predicate_expected_type",
    "json_structural_predicate_error",
    "json_structural_predicate_expected_type",
    "json_type_matches",
    "json_type_name",
    "local_http_url_error",
    "resolve_json_pointer",
    "strict_json_loads",
]
